services:
  postgres:
    build:
      context: .
      dockerfile: postgres.dockerfile
    image: "postgres-dwforbi"
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
       - dwforbi:/data/postgres-dwforbi
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
    dwforbi:
      external: true